# Generated by Django 5.0.7 on 2024-08-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, unique=True)),
                ('barcode', models.BigIntegerField(unique=True)),
                ('sell_price', models.FloatField()),
                ('qty_instock', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('create_by', models.BigIntegerField()),
                ('update_by', models.BigIntegerField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.category')),
            ],
        ),
    ]
