# Generated by Django 5.0.7 on 2024-08-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
